In [1]:
import numpy as np
import pandas as pd

import acquire

In [2]:
df = acquire.wrangle_data()

In [4]:
df = acquire.new_data()
df.isna().sum()

date               0
time               0
ip                 0
endpoint           1
user_id            0
cohort_id      52893
cohort_name    52893
slack          52893
start_date     52893
end_date       52893
program_id     52893
dtype: int64

In [7]:
df[df.endpoint.notna()]

,date,time,ip,endpoint,user_id,cohort_id,cohort_name,slack,start_date,end_date,program_id
0,2018-01-26,09:55:03,97.105.19.61,/,1,8.0,Hampton,#hampton,2015-09-22,2016-02-06,1.0
1,2018-01-26,09:56:02,97.105.19.61,java-ii,1,8.0,Hampton,#hampton,2015-09-22,2016-02-06,1.0
2,2018-01-26,09:56:05,97.105.19.61,java-ii/object-oriented-programming,1,8.0,Hampton,#hampton,2015-09-22,2016-02-06,1.0
3,2018-01-26,09:56:06,97.105.19.61,slides/object_oriented_programming,1,8.0,Hampton,#hampton,2015-09-22,2016-02-06,1.0
4,2018-01-26,09:56:24,97.105.19.61,javascript-i/conditionals,2,22.0,Teddy,#teddy,2018-01-08,2018-05-17,2.0
...,...,...,...,...,...,...,...,...,...,...,...
900218,2021-04-21,16:41:51,71.150.217.33,jquery/personal-site,64,28.0,Staff,#,2014-02-04,2014-02-04,2.0
900219,2021-04-21,16:42:02,71.150.217.33,jquery/mapbox-api,64,28.0,Staff,#,2014-02-04,2014-02-04,2.0
900220,2021-04-21,16:42:09,71.150.217.33,jquery/ajax/weather-map,64,28.0,Staff,#,2014-02-04,2014-02-04,2.0
900221,2021-04-21,16:44:37,24.160.137.86,anomaly-detection/discrete-probabilistic-methods,744,28.0,Staff,#,2014-02-04,2014-02-04,2.0
900222,2021-04-21,16:44:39,71.150.217.33,jquery/mapbox-api,64,28.0,Staff,#,2014-02-04,2014-02-04,2.0

In [3]:
df.head()

,endpoint,user_id,cohort_id,cohort_name,slack,start_date,end_date,program_id,program,module,lesson
datetime,,,,,,,,,,,
2018-01-26 09:55:03,/,1,8.0,Hampton,#hampton,2015-09-22 00:00:00,2016-02-06 00:00:00,1,Full Stack PHP,None,None
2018-01-26 09:56:02,java-ii,1,8.0,Hampton,#hampton,2015-09-22 00:00:00,2016-02-06 00:00:00,1,Full Stack PHP,java-ii,None
2018-01-26 09:56:05,java-ii/object-oriented-programming,1,8.0,Hampton,#hampton,2015-09-22 00:00:00,2016-02-06 00:00:00,1,Full Stack PHP,java-ii,object-oriented-programming
2018-01-26 09:56:06,slides/object_oriented_programming,1,8.0,Hampton,#hampton,2015-09-22 00:00:00,2016-02-06 00:00:00,1,Full Stack PHP,slides,object_oriented_programming
2018-01-26 09:56:24,javascript-i/conditionals,2,22.0,Teddy,#teddy,2018-01-08 00:00:00,2018-05-17 00:00:00,2,Full Stack Java,javascript-i,conditionals

In [23]:
df.shape

(847329, 11)

In [21]:
df.index.min(), df.index.max()

(Timestamp('2018-01-26 09:55:03'), Timestamp('2021-04-21 16:44:39'))

The data consists of log entries generated between January 2018 and April 2021

## Question

At some point in 2019, the ability for students and alumni to access both curriculums (web dev to ds, ds to web dev) should have been shut off. Do you see any evidence of that happening? Did it happen before?

### Determining curriculum belonging

In [4]:
df.endpoint.value_counts()

/                                                               45854
javascript-i                                                    18203
toc                                                             17591
search/search_index.json                                        17534
java-iii                                                        13166
                                                                ...
content/examples/javascript/primitive-types.html                    1
content/examples/javascript/conditionals.html                       1
2-storytelling/1-overview/www.qlik.com                              1
syntax-types-and-variables                                          1
appendix/professional-development/post-interview-review-form        1
Name: endpoint, Length: 2224, dtype: int64

In [9]:
df['module'] = None

In [12]:
trimmed = df[df.endpoint != '/']

In [22]:
module=  trimmed.endpoint.apply(lambda x: x.split('/')[0])
module.values

array(['java-ii', 'java-ii', 'slides', ..., 'jquery', 'anomaly-detection',
       'jquery'], dtype=object)

In [33]:
df.loc[df.endpoint != '/', 'resource']= module

In [34]:
df.head()

,endpoint,user_id,cohort_id,cohort_name,slack,start_date,end_date,program_id,program,resource,lesson
datetime,,,,,,,,,,,
2018-01-26 09:55:03,/,1,8.0,Hampton,#hampton,2015-09-22,2016-02-06,1,Full Stack PHP,None,
2018-01-26 09:56:02,java-ii,1,8.0,Hampton,#hampton,2015-09-22,2016-02-06,1,Full Stack PHP,java-ii,None
2018-01-26 09:56:05,java-ii/object-oriented-programming,1,8.0,Hampton,#hampton,2015-09-22,2016-02-06,1,Full Stack PHP,java-ii,object-oriented-programming
2018-01-26 09:56:06,slides/object_oriented_programming,1,8.0,Hampton,#hampton,2015-09-22,2016-02-06,1,Full Stack PHP,slides,object_oriented_programming
2018-01-26 09:56:24,javascript-i/conditionals,2,22.0,Teddy,#teddy,2018-01-08,2018-05-17,2,Full Stack Java,javascript-i,conditionals

In [27]:
def get_lesson(string):
    arr = string.split('/')
    if len(arr) > 1:
        return arr[1]
    else:
        return None

In [28]:
df['lesson'] = df.endpoint.apply(get_lesson)

In [29]:
df.head()

,endpoint,user_id,cohort_id,cohort_name,slack,start_date,end_date,program_id,program,resource,lesson
datetime,,,,,,,,,,,
2018-01-26 09:55:03,/,1,8.0,Hampton,#hampton,2015-09-22,2016-02-06,1,Full Stack PHP,None,
2018-01-26 09:56:02,java-ii,1,8.0,Hampton,#hampton,2015-09-22,2016-02-06,1,Full Stack PHP,java-ii,None
2018-01-26 09:56:05,java-ii/object-oriented-programming,1,8.0,Hampton,#hampton,2015-09-22,2016-02-06,1,Full Stack PHP,java-ii,object-oriented-programming
2018-01-26 09:56:06,slides/object_oriented_programming,1,8.0,Hampton,#hampton,2015-09-22,2016-02-06,1,Full Stack PHP,slides,object_oriented_programming
2018-01-26 09:56:24,javascript-i/conditionals,2,22.0,Teddy,#teddy,2018-01-08,2018-05-17,2,Full Stack Java,javascript-i,conditionals

In [30]:
df.lesson.value_counts()

                    45912
introduction        37414
fundamentals        34410
css-i               31590
css-ii              20260
                    ...
jpa                     1
formmodelbinding        1
form                    1
java-iii                1
explore-old             1
Name: lesson, Length: 669, dtype: int64

In [31]:
df[df.lesson == 'java-iii']

,endpoint,user_id,cohort_id,cohort_name,slack,start_date,end_date,program_id,program,resource,lesson
datetime,,,,,,,,,,,
2020-06-15 09:36:50,mysql/java-iii,495,51.0,Deimos,#deimos,2019-09-16,2020-02-27,2,Full Stack Java,mysql,java-iii

In [36]:
df.endpoint.apply(get_module)

datetime
2018-01-26 09:55:03
2018-01-26 09:56:02              java-ii
2018-01-26 09:56:05              java-ii
2018-01-26 09:56:06               slides
2018-01-26 09:56:24         javascript-i
                             ...
2021-04-21 16:41:51               jquery
2021-04-21 16:42:02               jquery
2021-04-21 16:42:09               jquery
2021-04-21 16:44:37    anomaly-detection
2021-04-21 16:44:39               jquery
Name: endpoint, Length: 847329, dtype: object

In [37]:
def get_lesson(string):
    arr = string.split('/')
    if len(arr) > 1:
        return arr[1]
    else:
        return None

def get_module(string):
    arr = string.split('/')
    return arr[0]

def parse_module_lesson(df):
    df['module'] = df.endpoint.apply(get_module)
    df['lesson'] = df.endpoint.apply(get_lesson)
    df = df.replace({'':None})
    return df

In [38]:
df = acquire.wrangle_data()

In [40]:
parse_module_lesson(df)

,endpoint,user_id,cohort_id,cohort_name,slack,start_date,end_date,program_id,program,module,lesson
datetime,,,,,,,,,,,
2018-01-26 09:55:03,/,1,8.0,Hampton,#hampton,2015-09-22 00:00:00,2016-02-06 00:00:00,1,Full Stack PHP,None,None
2018-01-26 09:56:02,java-ii,1,8.0,Hampton,#hampton,2015-09-22 00:00:00,2016-02-06 00:00:00,1,Full Stack PHP,java-ii,None
2018-01-26 09:56:05,java-ii/object-oriented-programming,1,8.0,Hampton,#hampton,2015-09-22 00:00:00,2016-02-06 00:00:00,1,Full Stack PHP,java-ii,object-oriented-programming
2018-01-26 09:56:06,slides/object_oriented_programming,1,8.0,Hampton,#hampton,2015-09-22 00:00:00,2016-02-06 00:00:00,1,Full Stack PHP,slides,object_oriented_programming
2018-01-26 09:56:24,javascript-i/conditionals,2,22.0,Teddy,#teddy,2018-01-08 00:00:00,2018-05-17 00:00:00,2,Full Stack Java,javascript-i,conditionals
...,...,...,...,...,...,...,...,...,...,...,...
2021-04-21 16:41:51,jquery/personal-site,64,28.0,Staff,#,2014-02-04 00:00:00,2014-02-04 00:00:00,2,Full Stack Java,jquery,personal-site
2021-04-21 16:42:02,jquery/mapbox-api,64,28.0,Staff,#,2014-02-04 00:00:00,2014-02-04 00:00:00,2,Full Stack Java,jquery,mapbox-api
2021-04-21 16:42:09,jquery/ajax/weather-map,64,28.0,Staff,#,2014-02-04 00:00:00,2014-02-04 00:00:00,2,Full Stack Java,jquery,ajax
2021-04-21 16:44:37,anomaly-detection/discrete-probabilistic-methods,744,28.0,Staff,#,2014-02-04 00:00:00,2014-02-04 00:00:00,2,Full Stack Java,anomaly-detection,discrete-probabilistic-methods
2021-04-21 16:44:39,jquery/mapbox-api,64,28.0,Staff,#,2014-02-04 00:00:00,2014-02-04 00:00:00,2,Full Stack Java,jquery,mapbox-api

### Investigation

In [18]:
df.program.value_counts()

Full Stack Java    713365
Data Science       103411
Full Stack PHP      30548
Front-End               5
Name: program, dtype: int64

In [24]:
df.groupby(['program']).module.value_counts().rename('count').reset_index()

            program                       module  count
0      Data Science                 fundamentals   8746
1      Data Science               classification   8620
2      Data Science               1-fundamentals   7945
3      Data Science                          sql   7505
4      Data Science                        3-sql   6165
..              ...                          ...    ...
829  Full Stack PHP                learn-to-code      1
830  Full Stack PHP  ordinary_least_squares.jpeg      1
831  Full Stack PHP                          php      1
832  Full Stack PHP                     pre-work      1
833  Full Stack PHP                        teams      1

[834 rows x 3 columns]

In [15]:
# df.endpoint.sort_values().unique().tolist()

In [17]:
df.module.sort_values().unique().tolist()

['%20https:',
 "'",
 ',%20https:',
 '.git',
 '.gitignore',
 '.well-known',
 '00_',
 '00_index',
 '01_intro',
 '02_listing_files',
 '03_file_paths',
 '04_navigating_the_filesystem',
 '05_creating_files_and_directories',
 '06_moving_files',
 '07_more_topics',
 '0_Classification_Algorithms',
 '1-fundamentals',
 '1-overview',
 '1.10_JobReq_Indeed',
 '1.2-data-science-pipeline',
 '1.3-pipeline-demo',
 '1._Fundamentals',
 '10-anomaly-detection',
 '10-nlp',
 '10.00_Intro',
 '10.00_Intro.html',
 '10.00_Intro.md',
 '10.01_Acquire_WebScraping',
 '10.02.01_ParseText',
 '10.02.02_POSTagging',
 '10.02.03_TFIDF',
 '10.03_Explore',
 '10.04.01_FeatureExtraction_FreqBased',
 '10.04.02_FeatureExtraction_Word2Vec',
 '10.04.03_SentimentAnalysis',
 '10.04.04_TextClassification',
 '10.04.05_TopicModeling',
 '10.10_Exercises',
 '10.1_Overview',
 '10.2_Regex',
 '10.3_Acquire',
 '10.4_Prepare',
 '10.5_Explore',
 '10.6_Model',
 '10._NLP',
 '10_Appendix_EntityLabeling',
 '10_Exercises',
 '10_Project',
 '10_Regex',
 '11-distributed-ml',
 '11-nlp',
 '11.00_Intro',
 '11.00_Intro.md',
 '11.01.01_ConnectingToSpark',
 '11.01.01_ConnectingToSpark.md',
 '11.01.02_DataAcquisition',
 '11.01.02_DataAcquisition.md',
 '11.01.03_Summarize.md',
 '11.01_GettingStarted',
 '11.02_DataAcquisition',
 '11.02_TransformData',
 '11.02_TransformData.md',
 '11.03_Explore.md',
 '11.03_Inspect',
 '11.04.01_Prepare_part1',
 '11.04.02_Prepare_part2',
 '11.04.03_Prepare_part3',
 '11.04.04_Prepare_part4',
 '11.04_Modeling.md',
 '11.05_Explore',
 '11.06.01_Model_TopicModeling',
 '11.06.02_Model_Classification',
 '11._DistributedML',
 '11._DistributedML.md',
 '115',
 '11_Environment_Setup',
 '11_Exercises',
 '11_SparkArchitecture',
 '12-advanced-topics',
 '12-distributed-ml',
 '12.01_SocialNetworkAnalysis',
 '12.02_Recommenders',
 '12.1_Tidy_Data',
 '12.2_Cross_Validation',
 '12.3.1_Virtual_Environments',
 '12.3.2_Building_A_Model',
 '12.3.3_Flask_Intro',
 '12.3.4_HTML_Templates',
 '12.3.5_HTML_Forms',
 '12.3.6_Page_Styling',
 '12.3.7_JSON_Responses',
 '12.3_Developing_Data_Products',
 '13-advanced-topics',
 '13-storytelling',
 '13.00_Intro.md',
 '13.01.01_Understand',
 '13.01.02.01_Prep',
 '13.01.02.02_TalkAndListen',
 '13.01.02.03_Sketch',
 '13.01.02.04_Prototype',
 '13.01.02_Create',
 '13.01.03_Refine',
 '13.01.04_Present',
 '13.02_Tableau',
 '13.03_Bokeh',
 '13.11_Exercises',
 '13.1_Understand',
 '13.2_Create',
 '13.3_Refine',
 '13.4_Present',
 '13.5_Tableau',
 '13._Storytelling',
 '130',
 '131',
 '132',
 '133',
 '135',
 '13_Appendix_BadCharts',
 '13_Appendix_ChartTypes',
 '13_Appendix_Keywords',
 '13_Exercises',
 '13_Overview',
 '167',
 '2-sql',
 '2-stats',
 '2-storytelling',
 '2.00.00_Excel_Prob_Stats',
 '2.00.01_Excel_Shortcuts',
 '2.00.01_Intro_Excel',
 '2.00.01_Navigating_Excel',
 '2.00.01_Navigating_Excel.md',
 '2.00.02_Gather_Excel',
 '2.00.02_Navigating_Excel',
 '2.00.03_Import_Excel',
 '2.00.03_PrepareData_Excel',
 '2.00.04_Explore_Analyze_Excel',
 '2.00.04_PrepareData_Excel',
 '2.00.05_Charts_PivotTables_Sparklines',
 '2.00.05_Explore_Viz_Excel',
 '2.00_About_Excel',
 '2.01.00_Descriptive_Stats',
 '2.01_Descriptive',
 '2.02.00_Inferential_Stats',
 '2.02.01_Distributions',
 '2.02.01_Probability',
 '2.02.02_Functions',
 '2.02.02_Sampling',
 '2.02.03_Power_Analysis',
 '2.02.04_Distribution_and_Test',
 '2.02.05_Compare_Means',
 '2.02.06_Correlation',
 '2.03.02_Sampling',
 '2.03.03_Power',
 '2.03.05_NormalityTests',
 '2.03.06_CorrelationTests',
 '2.0_Intro_Stats',
 '2.1-spreadsheets-overview',
 '2._Stats',
 '3-acquire',
 '3-data-types-and-variables',
 '3-databases',
 '3-discrete-probabilistic-methods',
 '3-probability-distributions',
 '3-python',
 '3-sql',
 '3-vocabulary',
 '3-vocabulary.md',
 '3.0-mysql-overview',
 '3.1-mysql-introduction',
 '3.10-more-exercises',
 '3.2-databases',
 '3.3-tables',
 '3.4-basic-statements',
 '3.5.0-clauses-overview',
 '3.5.1-where',
 '3.5.2-order-by',
 '3.5.3-limit',
 '3.6-functions',
 '3.7-group-by',
 '3.8.0-relationships-overview',
 '3.8.1-indexes',
 '3.8.2-joins',
 '3.8.3-subqueries',
 '3.9-temporary-tables',
 '4-detecting-timeseries-anomalies',
 '4-python',
 '4-stats',
 '4.0_overview',
 '4.1_introduction',
 '4.2-compare-means',
 '4.2_data_types_and_variables',
 '4.3_control_structures',
 '4.4_functions',
 '4.5-more-statistical-testing-examples',
 '4.5_imports',
 '4.6.0_DS_Libraries_Overview',
 '4.6.1_introduction_to_matplotlib',
 '4.6.2_introduction_to_numpy',
 '4.6.3_introduction_to_pandas',
 '4.6.4_introduction_to_seaborn',
 '4_Error_Handling',
 '4_Matplotlib_Styles',
 '4_Objects',
 '4_Projects',
 '4_introduction_to_sklearn',
 '4_list_comprehension_exercises',
 '4_panda_bears',
 '5-detecting-with-clustering',
 '5-regression',
 '5-stats',
 '5.00_Intro',
 '5.01_Acquire',
 '5.02_Prep',
 '5.03_Explore',
 '5.04.02_OrdinaryLeastSquares',
 '5.04.03_RidgeRegression',
 '5.04.04_LeastAngleRegression',
 '5.04.05_Exercises',
 '5.05_Deliver',
 '5.0_Intro_Regression',
 '5._Regression',
 '6-classification',
 '6-regression',
 '6-stats',
 '6.00_Intro',
 '6.00_Intro.md',
 '6.01.01_AcquireSQL',
 '6.01.02_Acquirecsv',
 '6.01.03_Summarize',
 '6.02.01_Prep',
 '6.02.02_MissingVals',
 '6.03_Explore',
 '6.04.01_Preprocessing',
 '6.04.02_DecisionTree',
 '6.04.03_KNN',
 '6.04.04_LogisticRegression',
 '6.04.05_SVM',
 '6.04.06_RandomForest',
 '6.04.07_Ensemble',
 '6.05_Deliver',
 '6.1_Overview',
 '6.2_About',
 '6.3_Acquire',
 '6.4_Prep',
 '6.5_Explore',
 '6.6.1_Logistic_Regression',
 '6.6.2_Decision_Tree',
 '6.6.3_Random_Forest',
 '6.6.4_KNN',
 '6._Classification',
 '6._Classification.md',
 '6_CustomFillNulls',
 '6_Ensemble',
 '6_Exercises',
 '6_Project',
 '6_SVM',
 '7-classification',
 '7-clustering',
 '7.00_Intro',
 '7.01_Acquire',
 '7.02_Prep',
 '7.03_Explore',
 '7.04.01_Partitioning',
 '7.04.02_Hierarchical',
 '7.0_Intro_Clustering',
 '7.1_Overview',
 '7.2_About',
 '7.3_Wrangle',
 '7.4.1-pandas-overview',
 '7.4.2-series',
 '7.4_Explore',
 '7.5.1_KMeans1',
 '7.5.2_KMeans2',
 '7._Clustering',
 '7_DBSCAN',
 '7_Exercises',
 '7_Project',
 '7_kmeans_by_hand',
 '8-clustering',
 '8-timeseries',
 '8.00_Intro',
 '8.01_Acquire',
 '8.02_Prep',
 '8.03_Explore',
 '8.04.02_ParametricModeling',
 '8.04.03_MLModeling',
 '8.05_Deliver',
 '8.0_Intro_Module',
 '8.1_Overview',
 '8.2_About',
 '8.3_Acquire',
 '8.4_Prep',
 '8.5_Explore',
 '8.6.1_ParametricModeling',
 '8.6.2_MLModeling',
 '8.6.2_Prophet',
 '8.7_Deliver',
 '8._Time_Series',
 '8._Time_Series.md',
 '8_Appendix_SVR',
 '8_Exercises',
 '8_Project',
 '9-anomaly-detection',
 '9-timeseries',
 '9.1_About',
 '9.20_Data',
 '9.2_Detect_through_Probability',
 '9.3_Detect_Through_Isolation_Forest',
 '9.3_Detecting_TimeSeries_Anomalies',
 '9.4_DBSCAN_to_detect_anomalies',
 '9.4_Detect_Through_Isolation_Forest',
 '9.4_Detecting_TimeSeries_Anomalies',
 '9.5_DBSCAN_to_detect_anomalies',
 '9.5_DBSCAN_to_detect_anomalies.md',
 '9._Anomaly_Detection',
 '9_Anomaly_Detection',
 '9_Appendix_Isolation_Forest',
 '9_Appendix_TSAD_Lesson',
 '9_Appendix_TSAD_Lesson2',
 '9_Appendix_TSAD_Lesson3',
 '9_Exercises',
 'A-clustering',
 'AI-ML-DL-timeline.jpg',
 'About_NLP',
 'AnomalyDetectionCartoon.jpeg',
 'Appendix_LeastAngleRegression',
 'Appendix_RidgeRegression',
 'Appendix_Tidy_Data',
 'BuiltIn_Datasets',
 'Classificaiton_LogisticRegression',
 'Classification_AcquireData',
 'Classification_DataPrep',
 'Classification_DecisionTree',
 'Classification_DecisionTree_files',
 'Classification_Exercises',
 'Classification_Explore',
 'Classification_KNN',
 'Classification_LogisticRegression',
 'Classification_LogisticRegression.md',
 'Classification_Project',
 'Classification_RandomForest',
 'Clustering_Acquire',
 'Clustering_Explore',
 'Clustering_Intro',
 'Clustering_Intro_Module',
 'Clustering_KMeans_1',
 'Clustering_KMeans_2',
 'Clustering_Prep.md',
 'Correlation.md',
 'DataSets_Elo_CustomerLoyalty',
 'DataToAction_v2.jpg',
 'Dataset_Challenge',
 'End_to_End_clustering',
 'Excel_Shortcuts',
 'Exercises',
 'Exploration_Lecture',
 'Hospital-Distance-Clusters.jpg',
 'Index.html',
 'Intro_to_Classification',
 'Intro_to_Classification_Module',
 'Intro_to_Regression',
 'Intro_to_Regression_Module',
 'MachineLearning_CheatSheet',
 'Model_NaiveBayes',
 'Module_6_Classification',
 'Multivariate_Regression_Excel',
 'Pipeline_Demo',
 'PreWork',
 'Probability.md',
 'RESTful-api',
 'Regression%20_Project.md',
 'Regression_Project',
 'Regression_Python',
 'SVM_NLP',
 'Selecting_a_hypothesis_test.svg',
 'Stats_Assessment',
 'Univariate_Regression_Excel',
 'Univariate_Regression_Python',
 'acquire',
 'acquire-and-prep',
 'ada-capsontes.html',
 'ada-python-assessment.html',
 'advanced-topics',
 'ajax',
 'ajax-api',
 'ajax-api-request.html',
 'aliases',
 'alumni',
 'alumni-tech-survey-2018',
 'alumni-tech-survey-2018.html',
 'annotations',
 'anomaly-detection',
 'api',
 'app',
 'appendix',
 'arash-arghavan',
 'arrays',
 'asdf',
 'asset-manifest.json',
 'assets',
 'b-clustering',
 'bad-charts',
 'basic-statements',
 'bayes-capstones',
 'bayes-python-assessment-4586.html',
 'bio',
 'bom-and-dom',
 'bonus-exercises',
 'capsones',
 'capstone',
 'capstone-workbook',
 'capstones',
 'case-statements',
 'cheatsheet.tex',
 'classical_programming_vs_machine_learning.jpeg',
 'classification',
 'cli',
 'cli-00-overview',
 'cli-01-intro',
 'cli-02-listing-files',
 'cli-03-file-paths',
 'cli-04-navigating-the-filesystem',
 'cli-05-creating-files-and-directories',
 'cli-06-moving-files',
 'cli-07-more-topics',
 'clustering',
 'code-standards',
 'codeup-exercises',
 'codeupexercises',
 'coding-challenges',
 'coffee-project',
 'coffee_consumption.csv',
 'cohorts',
 'collections',
 'compare-means',
 'conditionals',
 'console-io',
 'content',
 'content..',
 'control-statements-and-loops',
 'create',
 'creating-charts',
 'css',
 'css-i',
 'css-ii',
 'curie-python-assessemt',
 'curie-python-assessment',
 'curie-python-assessment.html',
 'curie-statistics-assessment',
 'curie-stats-assessment',
 'darden-python-assessment.html',
 'data',
 'data-1',
 'data-science',
 'data-science-modules.jpg',
 'data-science-pipeline',
 'database-design',
 'databases',
 'dataframes',
 'datascience',
 'decision-trees',
 'dendogram_sample.jpeg',
 'deployment-and-dependencies',
 'diagram-of-ds-pipeline-fraud-example.jpeg',
 'distributed-ml',
 'documentation',
 'ds',
 'easley-python-assessment.html',
 'effects',
 'elements',
 'end_to_end_clustering',
 'environment-setup',
 'es6',
 'essential-methods',
 'evaluate',
 'evaluation',
 'events',
 'examples',
 'exceptions-and-error-handling',
 'explore',
 'extra',
 'extra-',
 'extra-challenges',
 'extra-exercises',
 'extra-features',
 'f',
 'fer',
 'file-io',
 'file.dat',
 'find_me_curie!(12.3.19)',
 'finish-the-adlister',
 'florence-python-assessment.html',
 'forms',
 'functions',
 'fundamentals',
 'further-reading',
 'git',
 'github_repo_language.gif',
 'glossary',
 'grades',
 'group-by',
 'habn',
 'hand',
 'handout',
 'handouts',
 'hello-bayes-cohort-yall-are-awesome',
 'help',
 'hfdgafdja',
 'home',
 'html',
 'html-css',
 'htmle-css',
 'imports',
 'index',
 'index.html',
 'individual-project',
 'inheritance-and-polymorphism',
 'instructors',
 'interfaces-and-abstract-classes',
 'interview',
 'interview-questions',
 'intro-to-matplotlib',
 'introduction',
 'introduction-to-java',
 'introduction-to-matplotlib',
 'introduction-to-python',
 'itc%20-%20ml',
 'itc-ml',
 'j',
 'jacascript-i',
 'java',
 'java-1',
 'java-i',
 'java-ii',
 'java-iii',
 'javascri',
 'javascript',
 'javascript-',
 'javascript-1',
 'javascript-functions',
 'javascript-i',
 'javascript-ii',
 'javascript-with-html',
 'jdbc',
 'job-board',
 'job-portal',
 'joins',
 'jquery',
 'json-responses',
 'jsp-and-jstl',
 'jupiter',
 'learn-to-code',
 'login',
 'logouts',
 'loguout',
 'loops',
 'ltc',
 'ltc-ml',
 'ltc-python',
 'ltc.-ml',
 'mac-tips',
 'main',
 'main-pages_xXxXx.html',
 'mapbox-api',
 'methods',
 'mini_exercises',
 'misleading1_baseball.jpg',
 'misleading1_fox.jpg',
 'misleading3_deaths.jpg',
 'mkdocs',
 'ml-ltc',
 'ml-methodologies-drawing.jpg',
 'model',
 'modeling-lesson1',
 'modern-data-scientist.jpg',
 'modules',
 'mvc',
 'mysql',
 'mysql-introduction',
 'nlp',
 'npm',
 'object-oriented-programming',
 'objects',
 'one',
 'open_data',
 'ordinary_least_squares.jpeg',
 'overview',
 'pair-programming',
 'pandas-overview',
 'passwords',
 'php',
 'php_i',
 'phpinfo',
 'pre-work',
 'prep',
 'prepare',
 'present',
 'prework',
 'prework.com',
 'professional-development',
 'project',
 'promises',
 'python',
 'query',
 'quic',
 'quiz',
 'quiz115',
 'quiz118',
 'quize',
 'quizes',
 'quizzes',
 'refine',
 'register%20t',
 'register.',
 'register.html',
 'registerUser',
 'registration',
 'regression',
 'regular-expressions',
 'relationships',
 'repo-doc',
 'sample-database',
 'scale_features_or_not.svg',
 'search',
 'selectors',
 'sequel-pro',
 'series',
 'servlets',
 'sessions-and-cookies',
 'setup',
 'sgithubtudents',
 'short_evaluation',
 'simulation',
 'single-page.html',
 'slides',
 'slidesexceptions_and_errorhandlings',
 'spark-execution-diagram.svg',
 'spark-local-mode.svg',
 'split-and-scale',
 'spring',
 'sql',
 'sql.mysql-overview',
 'src',
 'statistics-assessment',
 'stats',
 'stats-assessment',
 'storytelling',
 'strings',
 'strudents',
 'student',
 'student-page',
 'students',
 'studentx',
 'study-session-with-ryan',
 'subqueries',
 'sw-project-planning',
 'syntax-types-and-variables',
 't9-solution',
 'tables',
 'tc-ml',
 'team',
 'team-setups',
 'teams',
 'testing-user-functions',
 'tidy-data',
 'timeline',
 'timeseries',
 'toc',
 'tools',
 'ui',
 'understand',
 'uploads',
 'user',
 'user-defined-functions.md',
 'user-input',
 'users',
 'users.json',
 'viz.py',
 'vocabulary',
 'warmups',
 'web-design',
 'web-dev-day-two',
 'where',
 'working-with-time-series-data',
 'wp-admin',
 'wp-login',
 None]

In [ ]:
kewords = {
    'web': [
        'java',
        'web',
        'php',
        'npm'
    ],

    'ds': [
        'data-sci',
        
    ]
}